name: 'setup-npmrc'
description: 'Setup .npmrc file'
author: 'Conventional Actions'
inputs:
  always-auth:
    description: 'Set always-auth in npmrc.'
    default: 'false'
  registry-url:
    description: 'Registry to set up for auth. Will set the registry in a project level .npmrc file.'
  scope:
    description: 'Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).'
  token:
    description: 'Token to use for authenticating to the registry'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: "purple"
  icon: "radio"
